# Generated by Django 3.2.9 on 2021-12-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
